name: Sync Upstream

on:
  schedule:
    - cron: '0 12 1 * *'  # 每月 1 号 UTC 时间 12:00 触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许推送到仓库

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史记录

      - name: 配置 Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: 添加上游仓库
        run: git remote add upstream https://github.com/ccbikai/Sink.git || echo "Remote already exists"

      - name: 拉取上游更新
        run: git fetch upstream

      - name: 合并上游更新（使用 merge 避免冲突中断）
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "Merge conflicts detected! Please resolve manually."

      - name: 检查是否有更新
        run: |
          if git log origin/main..HEAD --oneline | grep . > /dev/null 2>&1; then
            echo "Updates detected. Pushing to fork..."
            git push --force-with-lease origin main || git push --force origin main
          else
            echo "No updates to push."
            exit 0
          fi
